### ISSUE TITLE
Create HS-Post migration

### ISSUE THREAD

**Issue by veganstraightedge** [homesteading/homesteading_publisher#2]
Pull migrations out of individual HS:Publisher apps and into this engine.

**Comment by veganstraightedge** [comment]
Pull migrations out of individual HS:Publisher apps and into this engine.

**Comment by bookis** [comment]
- [x] Add Migrations to publisher
- [x] Remove migrations from publisher apps

K done.

**Comment by bookis** [comment]
@veganstraightedge You wanna double check I put all the needed fields in the migration then close?

**Comment by veganstraightedge** [comment]
Grood.
