### ISSUE TITLE
Extract non-DRY model methods from all publisher apps

### ISSUE THREAD

**Issue by veganstraightedge** [homesteading/homesteading_publisher#4]

**Comment by bookis** [comment]
@veganstraightedge what is with [this `Weight` class](https://github.com/homesteading/homesteading-weight/blame/master/app/models/weight.rb#L1) should it be a class named Weight? Or is it redundant, and these methods should be moved onto the `Post` class?

**Comment by veganstraightedge** [comment]
Looks like I just missed migrating that over to the engine.
It should be like the rest.

https://github.com/homesteading/homesteading-walk/blame/master/app/models/post.rb#L1

**Comment by bookis** [comment]
:+1:
